# Generated by Django 2.2.3 on 2019-08-19 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('age', models.IntegerField()),
                ('zodiak', models.CharField(choices=[('Водолей', 'Водолей'), ('Рыбы', 'Рыбы'), ('Овен', 'Овен'), ('Телец', 'Телец'), ('Близнецы', 'Близнецы'), ('Рак', 'Рак'), ('Лев', 'Лев'), ('Дева', 'Дева'), ('Весы', 'Весы'), ('Скорпион', 'Скорпион'), ('Стрелец', 'Стрелец'), ('Козерог', 'Козерог')], default='Водолей', max_length=13)),
                ('city', models.CharField(max_length=85)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('website', models.URLField(max_length=250)),
                ('tags', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
