# Generated by Django 2.2.3 on 2019-08-07 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_project', '0002_auto_20190731_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('zodiak', models.CharField(choices=[('Водолей', 'Водолей'), ('Рыбы', 'Рыбы'), ('Овен', 'Овен'), ('Телец', 'Телец'), ('Близнецы', 'Близнецы'), ('Рак', 'Рак'), ('Лев', 'Лев'), ('Дева', 'Дева'), ('Весы', 'Весы'), ('Скорпион', 'Скорпион'), ('Стрелец', 'Стрелец'), ('Козерог', 'Козерог')], default='Водолей', max_length=13)),
                ('city', models.CharField(max_length=85)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('website', models.URLField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
