# Generated by Django 2.2.3 on 2019-10-24 06:28

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0002_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direction',
            field=models.CharField(choices=[('ILLUSTRATOR', 'Художник-иллюстратор'), ('GRAPHIC', 'Художник-график'), ('CARTOONIST', 'Художник-карикатурист'), ('PAINTER', 'Живописец'), ('PORTRAIT', 'Художник-портретист')], default='ILLUSTRATOR', max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=360),
        ),
    ]
